// =============================================================
// ДАННЫЕ ТУРНИРА — этот файл правится вручную по ходу турнира.
// Больше нигде ничего трогать не нужно: сетка, список ближайших
// матчей и статистика рендерятся из того, что здесь написано.
// =============================================================

// -------------------------------------------------------------
// ПЕРСОНАЖИ. slug — короткий идентификатор без пробелов
// (используется в matches ниже), image — путь до портрета
// в assets/characters/. Пока картинок нет — покажется плейсхолдер
// с первой буквой имени, вёрстка не сломается.
// -------------------------------------------------------------
export const characters = {
  "sherlock-holmes": { name: "Шерлок Холмс", image: "assets/characters/sherlock-holmes.jpg" },
  "invisible-man": { name: "Человек-невидимка", image: "assets/characters/invisible-man.jpg" },
  "dracula": { name: "Дракула", image: "assets/characters/dracula.jpg" },
  "alice": { name: "Алиса", image: "assets/characters/alice.jpg" },
  // ... добавляйте остальных участников турнира по такому же образцу
};

// -------------------------------------------------------------
// ИГРОКИ. slug — короткий идентификатор (используется в matches).
// -------------------------------------------------------------
export const players = {
  "gleb": { name: "Глеб" },
  "anna": { name: "Анна" },
  "igor": { name: "Игорь" },
  "olesya": { name: "Олеся" },
  // ... добавляйте остальных игроков турнира по такому же образцу
};

// -------------------------------------------------------------
// МАТЧИ. Полная сетка на 32 участника уже собрана ниже (16 игр
// в 1/16, 8 в 1/8, 4 в 1/4, 2 в 1/2, 1 финал) — связи между
// раундами (nextMatchId/nextMatchSlot) готовы, их трогать не нужно.
//
// Как заполнять по ходу турнира:
//   1. Когда пара определилась — впишите slotA/slotB (player + character
//      как slug из словарей выше), поставьте status: "scheduled" и,
//      если знаете дату игры, scheduledDate: "YYYY-MM-DD".
//   2. Когда матч сыгран — поставьте status: "completed", winner: "A" или "B",
//      и заполните stats (кто ходил первым, на каком раунде закончилась
//      игра, сколько HP осталось у победителя, впечатления).
//   3. Победитель сам не переносится в следующий матч — впишите его
//      в slotA/slotB того матча, чей id указан в nextMatchId
//      (в слот nextMatchSlot).
//
// Первые два матча ниже — для примера (один сыгран, один запланирован).
// -------------------------------------------------------------
export const matches = [
  {
    id: "r32-1",
    stage: "1/16",
    roundIndex: 0,
    position: 0,
    slotA: { player: "gleb", character: "sherlock-holmes" },
    slotB: { player: "anna", character: "invisible-man" },
    status: "completed",
    scheduledDate: null,
    winner: "A",
    stats: {
      firstPlayer: "A",
      finalRound: 5,
      winnerHp: 6,
      notes: "Шерлок задавил ловушками у канализации, Невидимка не успел разогнаться.",
    },
    nextMatchId: "r16-1",
    nextMatchSlot: "A",
  },
  {
    id: "r32-2",
    stage: "1/16",
    roundIndex: 0,
    position: 1,
    slotA: { player: "igor", character: "dracula" },
    slotB: { player: "olesya", character: "alice" },
    status: "scheduled",
    scheduledDate: "2026-08-30",
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-1",
    nextMatchSlot: "B",
  },
  {
    id: "r32-3",
    stage: "1/16",
    roundIndex: 0,
    position: 2,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-2",
    nextMatchSlot: "A",
  },
  {
    id: "r32-4",
    stage: "1/16",
    roundIndex: 0,
    position: 3,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-2",
    nextMatchSlot: "B",
  },
  {
    id: "r32-5",
    stage: "1/16",
    roundIndex: 0,
    position: 4,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-3",
    nextMatchSlot: "A",
  },
  {
    id: "r32-6",
    stage: "1/16",
    roundIndex: 0,
    position: 5,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-3",
    nextMatchSlot: "B",
  },
  {
    id: "r32-7",
    stage: "1/16",
    roundIndex: 0,
    position: 6,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-4",
    nextMatchSlot: "A",
  },
  {
    id: "r32-8",
    stage: "1/16",
    roundIndex: 0,
    position: 7,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-4",
    nextMatchSlot: "B",
  },
  {
    id: "r32-9",
    stage: "1/16",
    roundIndex: 0,
    position: 8,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-5",
    nextMatchSlot: "A",
  },
  {
    id: "r32-10",
    stage: "1/16",
    roundIndex: 0,
    position: 9,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-5",
    nextMatchSlot: "B",
  },
  {
    id: "r32-11",
    stage: "1/16",
    roundIndex: 0,
    position: 10,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-6",
    nextMatchSlot: "A",
  },
  {
    id: "r32-12",
    stage: "1/16",
    roundIndex: 0,
    position: 11,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-6",
    nextMatchSlot: "B",
  },
  {
    id: "r32-13",
    stage: "1/16",
    roundIndex: 0,
    position: 12,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-7",
    nextMatchSlot: "A",
  },
  {
    id: "r32-14",
    stage: "1/16",
    roundIndex: 0,
    position: 13,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-7",
    nextMatchSlot: "B",
  },
  {
    id: "r32-15",
    stage: "1/16",
    roundIndex: 0,
    position: 14,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-8",
    nextMatchSlot: "A",
  },
  {
    id: "r32-16",
    stage: "1/16",
    roundIndex: 0,
    position: 15,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "r16-8",
    nextMatchSlot: "B",
  },
  {
    id: "r16-1",
    stage: "1/8",
    roundIndex: 1,
    position: 0,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "qf-1",
    nextMatchSlot: "A",
  },
  {
    id: "r16-2",
    stage: "1/8",
    roundIndex: 1,
    position: 1,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "qf-1",
    nextMatchSlot: "B",
  },
  {
    id: "r16-3",
    stage: "1/8",
    roundIndex: 1,
    position: 2,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "qf-2",
    nextMatchSlot: "A",
  },
  {
    id: "r16-4",
    stage: "1/8",
    roundIndex: 1,
    position: 3,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "qf-2",
    nextMatchSlot: "B",
  },
  {
    id: "r16-5",
    stage: "1/8",
    roundIndex: 1,
    position: 4,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "qf-3",
    nextMatchSlot: "A",
  },
  {
    id: "r16-6",
    stage: "1/8",
    roundIndex: 1,
    position: 5,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "qf-3",
    nextMatchSlot: "B",
  },
  {
    id: "r16-7",
    stage: "1/8",
    roundIndex: 1,
    position: 6,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "qf-4",
    nextMatchSlot: "A",
  },
  {
    id: "r16-8",
    stage: "1/8",
    roundIndex: 1,
    position: 7,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "qf-4",
    nextMatchSlot: "B",
  },
  {
    id: "qf-1",
    stage: "1/4",
    roundIndex: 2,
    position: 0,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "sf-1",
    nextMatchSlot: "A",
  },
  {
    id: "qf-2",
    stage: "1/4",
    roundIndex: 2,
    position: 1,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "sf-1",
    nextMatchSlot: "B",
  },
  {
    id: "qf-3",
    stage: "1/4",
    roundIndex: 2,
    position: 2,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "sf-2",
    nextMatchSlot: "A",
  },
  {
    id: "qf-4",
    stage: "1/4",
    roundIndex: 2,
    position: 3,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "sf-2",
    nextMatchSlot: "B",
  },
  {
    id: "sf-1",
    stage: "1/2",
    roundIndex: 3,
    position: 0,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "final",
    nextMatchSlot: "A",
  },
  {
    id: "sf-2",
    stage: "1/2",
    roundIndex: 3,
    position: 1,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: "final",
    nextMatchSlot: "B",
  },
  {
    id: "final",
    stage: "Финал",
    roundIndex: 4,
    position: 0,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
    },
    nextMatchId: null,
    nextMatchSlot: null,
  },
];
