// =============================================================
// ДАННЫЕ ТУРНИРА — этот файл правится вручную по ходу турнира.
// Больше нигде ничего трогать не нужно: сетка, список ближайших
// матчей, страница матча и статистика рендерятся из того, что
// здесь написано.
// =============================================================

// -------------------------------------------------------------
// ПЕРСОНАЖИ. slug — короткий идентификатор без пробелов
// (используется в matches ниже). sidekick — необязательное имя
// сайдкика, показывается второй строкой мельче и серым (кроме
// компактных мест вроде превью матча в сетке — там оно скрыто,
// чтобы не перегружать карточку). image — путь до портрета
// в assets/characters/. Пока картинок нет — покажется плейсхолдер
// с первой буквой имени, вёрстка не сломается.
// -------------------------------------------------------------
export const characters = {
  "t-rex": { name: "Ти-рекс", image: "assets/characters/t-rex.webp" },
  "sherlock-holmes": { name: "Шерлок Холмс", sidekick: "и доктор Ватсон", image: "assets/characters/sherlock-holmes.webp" },
  "bloody-mary": { name: "Кровавая Мэри", image: "assets/characters/bloody-mary.webp" },
  "jekyll-hyde": { name: "Джекил и Хайд", image: "assets/characters/jekyll-hyde.webp" },
  "jinn": { name: "Джинн", image: "assets/characters/jinn.webp" },
  "invisible-man": { name: "Невидимка", image: "assets/characters/invisible-man.webp" },
  "houdini": { name: "Гудини", sidekick: "и Бесс", image: "assets/characters/houdini.webp" },
  "achilles": { name: "Ахиллес", sidekick: "и Патрокл", image: "assets/characters/achilles.webp" },
  "ellie-sattler": { name: "Д-р Элли Сэттлер", sidekick: "и Д-р Иэн Малькольм", image: "assets/characters/ellie-sattler.webp" },
  "dracula": { name: "Дракула", sidekick: "и Сёстры", image: "assets/characters/dracula.webp" },
  "raptors": { name: "Рапторы", image: "assets/characters/raptors.webp" },
  "yennenga": { name: "Йенненга", sidekick: "и лучники", image: "assets/characters/yennenga.webp" },
  "beowulf": { name: "Беовульф", sidekick: "и Виглаф", image: "assets/characters/beowulf.webp" },
  "blackbeard": { name: "Чёрная Борода", sidekick: "и Морские Волки", image: "assets/characters/blackbeard.webp" },
  "hamlet": { name: "Гамлет", sidekick: "и Розенкранц и Гильденстерн", image: "assets/characters/hamlet.webp" },
  "shakespeare": { name: "Шекспир", sidekick: "и Актёры", image: "assets/characters/shakespeare.webp" },
  "robin-hood": { name: "Робин Гуд", sidekick: "и разбойники", image: "assets/characters/robin-hood.webp" },
  "tomoe-gozen": { name: "Томоэ Годзэн", image: "assets/characters/tomoe-gozen.webp" },
  "king-arthur": { name: "Король Артур", sidekick: "и Мерлин", image: "assets/characters/king-arthur.webp" },
  "sun-wukong": { name: "Сунь Укун", sidekick: "и Двойники", image: "assets/characters/sun-wukong.webp" },
  "little-red-riding-hood": { name: "Красная Шапочка", sidekick: "и Охотник", image: "assets/characters/little-red-riding-hood.webp" },
  "robert-muldoon": { name: "Роберт Малдуин", sidekick: "и работники \"Инген\"", image: "assets/characters/robert-muldoon.webp" },
  "bigfoot": { name: "Бигфут", sidekick: "и Кролень", image: "assets/characters/bigfoot.webp" },
  "titania": { name: "Титания", sidekick: "и Оберон", image: "assets/characters/titania.webp" },
  "medusa": { name: "Медуза", sidekick: "и Гарпии", image: "assets/characters/medusa.webp" },
  "loki": { name: "Локи", image: "assets/characters/loki.webp" },
  "sindbad": { name: "Синдбад", sidekick: "и Носильщик", image: "assets/characters/sindbad.webp" },
  "weird-sisters": { name: "Вещие Сёстры", image: "assets/characters/weird-sisters.webp" },
  "alice": { name: "Алиса", sidekick: "и Бармаглот", image: "assets/characters/alice.webp" },
  "chupacabra": { name: "Чупакабра", image: "assets/characters/chupacabra.webp" },
  "oda-nobunaga": { name: "Ода Нобунага", sidekick: "и Самураи", image: "assets/characters/oda-nobunaga.webp" },
  "pandora": { name: "Пандора", sidekick: "и Какодемоны", image: "assets/characters/pandora.webp" },
};

// -------------------------------------------------------------
// ИГРОКИ турнира (сейчас их двое — каждый матч они распределяют
// между собой, кто каким персонажем играет).
// -------------------------------------------------------------
export const players = {
  "roma": { name: "Рома" },
  "gleb": { name: "Глеб" },
};

// -------------------------------------------------------------
// КАРТЫ. Пул из 15 карт (игровых карт-локаций), одна из которых
// случайно достаётся каждому матчу (кнопка на странице матча).
// -------------------------------------------------------------
export const cards = {
  "baskerville-manor": { name: "Baskerville Manor", image: "assets/cards/baskerville-manor.webp" },
  "globe-theatre": { name: "Globe Theatre", image: "assets/cards/globe-theatre.webp" },
  "hanging-gardens": { name: "Hanging Gardens", image: "assets/cards/hanging-gardens.webp" },
  "marmoreal": { name: "Marmoreal", image: "assets/cards/marmoreal.webp" },
  "santas-workshop": { name: "Santa's Workshop", image: "assets/cards/santas-workshop.avif" },
  "sarpedon": { name: "Sarpedon", image: "assets/cards/sarpedon.webp" },
  "soho": { name: "Soho", image: "assets/cards/soho.webp" },
  "venice": { name: "Venice", image: "assets/cards/venice.avif" },
  "azuchi-castle": { name: "Azuchi Castle", image: "assets/cards/azuchi-castle.webp" },
  "heorot": { name: "Heorot", image: "assets/cards/heorot.webp" },
  "king-solomons-mine": { name: "King Solomon's Mine", image: "assets/cards/king-solomons-mine.webp" },
  "raptor-paddock": { name: "Raptor Paddock", image: "assets/cards/raptor-paddock.webp" },
  "sherwood-forest": { name: "Sherwood Forest", image: "assets/cards/sherwood-forest.webp" },
  "t-rex-paddock": { name: "T. Rex Paddock", image: "assets/cards/t-rex-paddock.webp" },
  "yukon": { name: "Yukon", image: "assets/cards/yukon.webp" },
};

// -------------------------------------------------------------
// ПОРЯДОК РОЗЫГРЫША КАРТ. Список id матчей в том порядке, в котором
// им реально доставалась карта (не порядок сетки, а порядок по
// факту розыгрыша!). Каждая карта не может выпасть повторно, пока
// не будут розыграны все остальные 14 — то есть до 15-го розыгрыша,
// потом колода "перетасовывается" заново для матчей 16-30, и так далее.
//
// Когда вписываете карту матчу (поле card) — допишите id этого матча
// в конец массива ниже, иначе розыгрыш не будет учтён при следующих
// подборах.
// -------------------------------------------------------------
export const cardDrawOrder = ["r32-1", "r32-2", "r32-3", "r32-4", "r32-5", "r32-6", "r32-7", "r32-8", "r32-9", "r32-10", "r32-11", "r32-12", "r32-13", "r32-14", "r32-15", "r32-16", "r16-1", "r16-2", "r16-3", "r16-4", "r16-5", "r16-6", "r16-7", "r16-8", "qf-1", "qf-2", "qf-3", "qf-4", "sf-1", "sf-2", "final", "third-place"];

// -------------------------------------------------------------
// МАТЧИ. Полная сетка на 32 участника уже собрана ниже (16 игр
// в 1/16, 8 в 1/8, 4 в 1/4, 2 в 1/2, 1 финал) — связи между
// раундами (nextMatchId/nextMatchSlot) готовы, их трогать не нужно.
// Персонажи первого раунда (1/16) уже расставлены по официальной
// сетке турнира. Последний элемент массива — отдельный матч "third-
// place" (за 3-е место, между проигравшими полуфиналов sf-1/sf-2);
// он не входит в сетку на выбывание (nextMatchId у него нет), в
// bracket.js отрисовывается отдельно рядом с финалом.
//
// Как заполнять по ходу турнира:
//   1. Если нужно уточнить/поменять дату — впишите scheduledDate:
//      "YYYY-MM-DD".
//   2. Карту, то, кто из игроков за кого играет, и кто ходит первым
//      (firstMove: "A" или "B") впишите сюда сами — можно заранее,
//      задолго до самой игры. Card и cardDrawOrder — как раньше.
//      firstMove для 1/16 не нужен (там жёсткое правило: всегда
//      slotA), а для 1/8 и дальше считается по алгоритму "первый ход
//      / игрок за раунд 2+" — см. память сессии (или спросите
//      заново, если начинается новая сессия: правило запомнено как
//      факт о проекте). Пока status матча не "completed", карта и
//      игроки показываются на сайте под спойлером ("Показать"),
//      чтобы не спалить их раньше времени — а вот firstMove не
//      секрет и показывается сразу открыто (плюс определяет, кто
//      в сетке/на странице матча рисуется сверху/слева).
//   3. Когда матч сыгран — поставьте status: "completed", winner:
//      "A" или "B", и заполните stats (кто ходил первым — то же
//      значение, что в firstMove, если правило не нарушили, — на
//      каком раунде закончилась игра, сколько HP осталось у
//      победителя, впечатления, rating — оценка игры от 1 до 5).
//      Спойлер с картой/игроками после этого сам исчезает — они
//      показываются в открытую.
//   3а. Когда сыграны sf-1 и sf-2 — впишите проигравших (не
//      победителей!) в slotA/slotB матча "third-place" и поставьте
//      ему status: "scheduled".
//   4. Победитель сам не переносится в следующий матч — впишите его
//      в slotA/slotB того матча, чей id указан в nextMatchId
//      (в слот nextMatchSlot), когда пары следующего раунда
//      определятся, заодно поставьте тому матчу status: "scheduled"
//      и посчитайте для него firstMove/игроков по тому же алгоритму.
// -------------------------------------------------------------
export const matches = [
  {
    id: "r32-1",
    stage: "1/16",
    roundIndex: 0,
    position: 0,
    slotA: { player: "roma", character: "t-rex" },
    slotB: { player: "gleb", character: "sherlock-holmes" },
    status: "completed",
    scheduledDate: null,
    card: "king-solomons-mine",
    firstMove: null,
    winner: "A",
    stats: {
      firstPlayer: "A",
      finalRound: 13,
      winnerHp: 16,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-1",
    nextMatchSlot: "A",
  },
  {
    id: "r32-2",
    stage: "1/16",
    roundIndex: 0,
    position: 1,
    slotA: { player: "roma", character: "jekyll-hyde" },
    slotB: { player: "gleb", character: "bloody-mary" },
    status: "completed",
    scheduledDate: null,
    card: "sarpedon",
    firstMove: null,
    winner: "B",
    stats: {
      firstPlayer: "A",
      finalRound: 22,
      winnerHp: 4,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-1",
    nextMatchSlot: "B",
  },
  {
    id: "r32-3",
    stage: "1/16",
    roundIndex: 0,
    position: 2,
    slotA: { player: "gleb", character: "jinn" },
    slotB: { player: "roma", character: "invisible-man" },
    status: "completed",
    scheduledDate: null,
    card: "azuchi-castle",
    firstMove: null,
    winner: "A",
    stats: {
      firstPlayer: "A",
      finalRound: 15,
      winnerHp: 8,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-2",
    nextMatchSlot: "A",
  },
  {
    id: "r32-4",
    stage: "1/16",
    roundIndex: 0,
    position: 3,
    slotA: { player: "gleb", character: "houdini" },
    slotB: { player: "roma", character: "achilles" },
    status: "completed",
    scheduledDate: null,
    card: "t-rex-paddock",
    firstMove: null,
    winner: "B",
    stats: {
      firstPlayer: "A",
      finalRound: 24,
      winnerHp: 4,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-2",
    nextMatchSlot: "B",
  },
  {
    id: "r32-5",
    stage: "1/16",
    roundIndex: 0,
    position: 4,
    slotA: { player: "roma", character: "ellie-sattler" },
    slotB: { player: "gleb", character: "dracula" },
    status: "completed",
    scheduledDate: null,
    card: "raptor-paddock",
    firstMove: null,
    winner: "B",
    stats: {
      firstPlayer: "A",
      finalRound: 26,
      winnerHp: 7,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-3",
    nextMatchSlot: "A",
  },
  {
    id: "r32-6",
    stage: "1/16",
    roundIndex: 0,
    position: 5,
    slotA: { player: "gleb", character: "raptors" },
    slotB: { player: "roma", character: "yennenga" },
    status: "completed",
    scheduledDate: null,
    card: "soho",
    firstMove: null,
    winner: "A",
    stats: {
      firstPlayer: "A",
      finalRound: 19,
      winnerHp: 7,
      notes: "Была мощнейшая комбуха на 4 доп действия со стороны динозавриков.",
      rating: null,
    },
    nextMatchId: "r16-3",
    nextMatchSlot: "B",
  },
  {
    id: "r32-7",
    stage: "1/16",
    roundIndex: 0,
    position: 6,
    slotA: { player: "gleb", character: "beowulf" },
    slotB: { player: "roma", character: "blackbeard" },
    status: "completed",
    scheduledDate: null,
    card: "heorot",
    firstMove: null,
    winner: "B",
    stats: {
      firstPlayer: "A",
      finalRound: 34,
      winnerHp: 3,
      notes: "У обоих бородачей кончились карты, но Беовульфа больше покоцали.",
      rating: null,
    },
    nextMatchId: "r16-4",
    nextMatchSlot: "A",
  },
  {
    id: "r32-8",
    stage: "1/16",
    roundIndex: 0,
    position: 7,
    slotA: { player: "roma", character: "hamlet" },
    slotB: { player: "gleb", character: "shakespeare" },
    status: "completed",
    scheduledDate: null,
    card: "sherwood-forest",
    firstMove: null,
    winner: "A",
    stats: {
      firstPlayer: "A",
      finalRound: 11,
      winnerHp: 7,
      notes: "У Розенкранца и Гильденстерна ещё +1 HP сверху. Шекспир пытался что-то противопоставить, но в неудачный момент кончились защитные карты и получил 10 урона в ебало за один ход.",
      rating: null,
    },
    nextMatchId: "r16-4",
    nextMatchSlot: "B",
  },
  {
    id: "r32-9",
    stage: "1/16",
    roundIndex: 0,
    position: 8,
    slotA: { player: null, character: "robin-hood" },
    slotB: { player: null, character: "tomoe-gozen" },
    status: "scheduled",
    scheduledDate: null,
    card: "globe-theatre",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-5",
    nextMatchSlot: "A",
  },
  {
    id: "r32-10",
    stage: "1/16",
    roundIndex: 0,
    position: 9,
    slotA: { player: null, character: "king-arthur" },
    slotB: { player: null, character: "sun-wukong" },
    status: "scheduled",
    scheduledDate: null,
    card: "baskerville-manor",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-5",
    nextMatchSlot: "B",
  },
  {
    id: "r32-11",
    stage: "1/16",
    roundIndex: 0,
    position: 10,
    slotA: { player: null, character: "little-red-riding-hood" },
    slotB: { player: null, character: "robert-muldoon" },
    status: "scheduled",
    scheduledDate: null,
    card: "hanging-gardens",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-6",
    nextMatchSlot: "A",
  },
  {
    id: "r32-12",
    stage: "1/16",
    roundIndex: 0,
    position: 11,
    slotA: { player: null, character: "bigfoot" },
    slotB: { player: null, character: "titania" },
    status: "scheduled",
    scheduledDate: null,
    card: "marmoreal",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-6",
    nextMatchSlot: "B",
  },
  {
    id: "r32-13",
    stage: "1/16",
    roundIndex: 0,
    position: 12,
    slotA: { player: null, character: "medusa" },
    slotB: { player: null, character: "loki" },
    status: "scheduled",
    scheduledDate: null,
    card: "santas-workshop",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-7",
    nextMatchSlot: "A",
  },
  {
    id: "r32-14",
    stage: "1/16",
    roundIndex: 0,
    position: 13,
    slotA: { player: null, character: "sindbad" },
    slotB: { player: null, character: "weird-sisters" },
    status: "scheduled",
    scheduledDate: null,
    card: "venice",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-7",
    nextMatchSlot: "B",
  },
  {
    id: "r32-15",
    stage: "1/16",
    roundIndex: 0,
    position: 14,
    slotA: { player: null, character: "alice" },
    slotB: { player: null, character: "chupacabra" },
    status: "scheduled",
    scheduledDate: null,
    card: "yukon",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-8",
    nextMatchSlot: "A",
  },
  {
    id: "r32-16",
    stage: "1/16",
    roundIndex: 0,
    position: 15,
    slotA: { player: null, character: "oda-nobunaga" },
    slotB: { player: null, character: "pandora" },
    status: "scheduled",
    scheduledDate: null,
    card: "soho",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "r16-8",
    nextMatchSlot: "B",
  },
  {
    id: "r16-1",
    stage: "1/8",
    roundIndex: 1,
    position: 0,
    slotA: { player: "gleb", character: "t-rex" },
    slotB: { player: "roma", character: "bloody-mary" },
    status: "scheduled",
    scheduledDate: null,
    card: "santas-workshop",
    firstMove: "B",
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "qf-1",
    nextMatchSlot: "A",
  },
  {
    id: "r16-2",
    stage: "1/8",
    roundIndex: 1,
    position: 1,
    slotA: { player: "roma", character: "jinn" },
    slotB: { player: "gleb", character: "achilles" },
    status: "scheduled",
    scheduledDate: null,
    card: "venice",
    firstMove: "B",
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "qf-1",
    nextMatchSlot: "B",
  },
  {
    id: "r16-3",
    stage: "1/8",
    roundIndex: 1,
    position: 2,
    slotA: { player: "roma", character: "dracula" },
    slotB: { player: "gleb", character: "raptors" },
    status: "scheduled",
    scheduledDate: null,
    card: "heorot",
    firstMove: "A",
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "qf-2",
    nextMatchSlot: "A",
  },
  {
    id: "r16-4",
    stage: "1/8",
    roundIndex: 1,
    position: 3,
    slotA: { player: "gleb", character: "blackbeard" },
    slotB: { player: "roma", character: "hamlet" },
    status: "scheduled",
    scheduledDate: null,
    card: "marmoreal",
    firstMove: "A",
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "qf-2",
    nextMatchSlot: "B",
  },
  {
    id: "r16-5",
    stage: "1/8",
    roundIndex: 1,
    position: 4,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "globe-theatre",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "qf-3",
    nextMatchSlot: "A",
  },
  {
    id: "r16-6",
    stage: "1/8",
    roundIndex: 1,
    position: 5,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "sherwood-forest",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "qf-3",
    nextMatchSlot: "B",
  },
  {
    id: "r16-7",
    stage: "1/8",
    roundIndex: 1,
    position: 6,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "raptor-paddock",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "qf-4",
    nextMatchSlot: "A",
  },
  {
    id: "r16-8",
    stage: "1/8",
    roundIndex: 1,
    position: 7,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "sarpedon",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "qf-4",
    nextMatchSlot: "B",
  },
  {
    id: "qf-1",
    stage: "1/4",
    roundIndex: 2,
    position: 0,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "hanging-gardens",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "sf-1",
    nextMatchSlot: "A",
  },
  {
    id: "qf-2",
    stage: "1/4",
    roundIndex: 2,
    position: 1,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "azuchi-castle",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "sf-1",
    nextMatchSlot: "B",
  },
  {
    id: "qf-3",
    stage: "1/4",
    roundIndex: 2,
    position: 2,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "baskerville-manor",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "sf-2",
    nextMatchSlot: "A",
  },
  {
    id: "qf-4",
    stage: "1/4",
    roundIndex: 2,
    position: 3,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "t-rex-paddock",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "sf-2",
    nextMatchSlot: "B",
  },
  {
    id: "sf-1",
    stage: "1/2",
    roundIndex: 3,
    position: 0,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "king-solomons-mine",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "final",
    nextMatchSlot: "A",
  },
  {
    id: "sf-2",
    stage: "1/2",
    roundIndex: 3,
    position: 1,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "yukon",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: "final",
    nextMatchSlot: "B",
  },
  {
    id: "final",
    stage: "Финал",
    roundIndex: 4,
    position: 0,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "hanging-gardens",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: null,
    nextMatchSlot: null,
  },
  {
    id: "third-place",
    stage: "Матч за 3-е место",
    roundIndex: 4,
    position: 1,
    slotA: { player: null, character: null },
    slotB: { player: null, character: null },
    status: "tbd",
    scheduledDate: null,
    card: "marmoreal",
    firstMove: null,
    winner: null,
    stats: {
      firstPlayer: null,
      finalRound: null,
      winnerHp: null,
      notes: "",
      rating: null,
    },
    nextMatchId: null,
    nextMatchSlot: null,
  },
];
